### ISSUE TITLE
Load order images

### ISSUE THREAD

**Issue by aubergine10** [totaljs/documentation#19]
Are these any use for the documentation?

![order](https://cloud.githubusercontent.com/assets/1386719/14939712/1a27bb02-0f4b-11e6-929e-b45668d9f1d2.png)
![modules](https://cloud.githubusercontent.com/assets/1386719/14939713/24ebd7bc-0f4b-11e6-8617-863daa7b9292.png)
![packages](https://cloud.githubusercontent.com/assets/1386719/14939714/2879d8c0-0f4b-11e6-9f14-5b69ed2d54e4.png)
![models](https://cloud.githubusercontent.com/assets/1386719/14939715/2daa3f74-0f4b-11e6-977b-8afae3c08c39.png)
![themes](https://cloud.githubusercontent.com/assets/1386719/14939716/3295ef1a-0f4b-11e6-8c46-9afb62d22efb.png)
![definitions](https://cloud.githubusercontent.com/assets/1386719/14939718/378f3da0-0f4b-11e6-96b1-018754485b5c.png)
![controllers](https://cloud.githubusercontent.com/assets/1386719/14939719/3b9142cc-0f4b-11e6-8840-88c97ef25126.png)

**Comment by petersirka** [comment]
I think that yes --> but too much options. I think that the first line decribes everything.

**Comment by aubergine10** [comment]
They are all separate images, so I was thinking that only one row would be shown at a time.

For example, on the [modules overview page](http://docs.totaljs.com/v2.0.x/en.html#pages~Modules) the red text at top would be replaced with `<img src="/path/to/img/modules.png" />` so the user sees the full sequence graphically represented but also the current step (depending on what page they are viewing) would be indicated.

Extra points would be awarded for [making an image map](http://imagemap-generator.dariodomi.de/) to link each step to the relevant overview page.

**Comment by petersirka** [comment]
Good idea.
I'll add it to documentation.
