### ISSUE TITLE
Version independent URLs to docs?

### ISSUE THREAD

**Issue by aubergine10** [totaljs/documentation#20]
It would be useful if there was some version-agnostic way to link to the docs - currently I have to link to a specific documentation version, for example:

* http://docs.totaljs.com/v2.0.x/en.html#api~FrameworkController~controller.isTransfer

This means that over time, whatever links to the docs will contain outdated links. It would be nice if there was a `release` URL that always points to the documentation for the current release, for example:

* http://docs.totaljs.com/release/en.html#api~FrameworkController~controller.isTransfer

That would remove the need to keep updating links to docs as they'd always link to current stable release.

**Comment by petersirka** [comment]
@aubergine10 I understand, good idea. I'll create it.

**Comment by aubergine10** [comment]
Maybe `current` or `master` would be better than `release`...?

**Comment by petersirka** [comment]
Or `latest`?

**Comment by aubergine10** [comment]
Yup, `latest` is even better. 👍

**Comment by petersirka** [comment]
I have added it: <http://docs.totaljs.com/latest/en.html>.
