### ISSUE TITLE
A typo in database documentation

### ISSUE THREAD

**Issue by gamtiq** [totaljs/documentation#21]
There is a typo in [Database documentation page](https://docs.totaljs.com/latest/en.html#api~Database):
> It's very great *databse* for very small projects

Also there is a typo in [Controllers documentation](https://docs.totaljs.com/latest/en.html#pages~Controllers):
> This function is used for debug purposes and should *reutrn* an object

**Comment by petersirka** [comment]
Thank you! I have fixed it... I prepare a new version, so I'll refresh docs maybe next week.
